### PR TITLE
Add mac dependencies

### PR DESCRIPTION
**Pull request by Timmmm**
(Not including Xcode)

### CODE REVIEW

**Comment by eyelash** [comment]
Does it actually work on macOS?

**Comment by Timmmm** [comment]
Yes! Although none of the icons (save, load, etc) load for some reason. And there's no horizontal scrolling but I think that's a known bug?

**Comment by eyelash** [comment]
That's cool. Can you post a screenshot?

Horizontal scrolling is not yet implemented (I was hoping to see an efficient implementation of line wrapping so horizontal scrolling would not be needed).

**Comment by Timmmm** [comment]
Will do (just on my way to Thailand so will be a couple of weeks!)

I think word wrap won't eliminate the need for horizontal scroll so you
should plan on implementing both. Also a couple of other considerations:

1. Xcode has "smart word wrap" (I guess you would call it) which wraps code
as if it were done manually (i.e. increase the indentation by 1). It's
pretty nice. Would be worth doing that.
2. Virtually all editors I've used have *terrible* performance with long
lines (2000+ characters). It would be great if that wasn't the case with
this. At the moment it is the fastest editor for long-line files I've found
(second is Sublime Text) but I guess that might be because it just ignores
most of the line.

**Pull request closed without merging**
