### PR TITLE
add C-q hotkey for quit

### PR DESCRIPTION
**Pull request by sp3d**
going through window.close() triggers the same logic as clicking the close button on window decoration, so this will work with any confirmation logic we may implement later

### CODE REVIEW

**Comment by eyelash** [comment]
I wonder whether we should integrate this with the application menu as well.

**Comment by sp3d** [comment]
Is it ok to commit this change so users can close the program the way they expect of GTK+ programs, and discuss future plans in a bug?

**Comment by eyelash** [comment]
Yeah, but xi-gtk is still very much in alpha state and not really usable as an editor so I don't think an intermediate solution is worth that much.

**Comment by eyelash** [comment]
Anyway, could you please add the shortcut to the README as well?

**Pull request merged**
