### PR TITLE
Specify xi-core location by environment variable

### PR DESCRIPTION
**Pull request by JesseFarebro**
I thought I'd send in my first PR just to let you know I'll be contributing to this repo now instead of mine. I'll start hacking away so we can try to achieve parity with the swift front-end.

### CODE REVIEW

**Comment by eyelash** [comment]
thanks :)
I guess I will grant you commit rights to the repository once I am sure our goals align and your code quality meets my standards.

**Comment by JesseFarebro** [comment]
@eyelash do you have some type of IM or we can make a Slack/Gitter channel to talk about some of our goals in?

**Comment by eyelash** [comment]
BTW I'm working on making Control-S a shortcut to save the current tab right now just so we don't waste efforts accidentally working on the same feature simultaneously.

**Comment by JesseFarebro** [comment]
@eyelash Sounds good, there seems to be a bug when you type a single character on a blank line and backspace that character the cursor stays drawn on the 1st column of that row. I'll be tackling that!

**Comment by eyelash** [comment]
@JesseFarebro I added a gitter chat: https://gitter.im/eyelash/xi-gtk

**Pull request merged**
